package com.ibm.Zimulator.Zimulator;
/*  
   This file is dynamically generated by CompileToJar.sh to contain the fresh version string seen below.
*/ 
public class Version
{
    public String V;
    public Version()
    {
         V="Version:5.000  Built:2019-01-08.15:33";  // Version:5.000  Built:2019-01-08.15:33 is replaced by building script.
    }
}
